editor: vi
executors:
  default:
    type: local
    description: submit jobs on local machine
config:
  paths:
    get_repo_path: /tmp/buildtest/repos
    buildspec_path: "/tmp/buildtest/repos:/home"
    testdir: /tmp/buildtest/test